bank_pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pos.urls')),
    path('', include('bank.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from . import views

app_name = "pos"

urlpatterns = [
    path('', views.index, name="index"),
    path('pos/login/', LoginView.as_view(), name="login"),
    path('pos/logout/', LogoutView.as_view(), name="logout"),
    path('pos/admin/', admin.site.urls, name='admin'),
    path('pos/index/', views.pos_index, name='pos_index'),
    path('pos/products/list/', views.products_list, name='products_list'),
    path('pos/products/add_purchase/', views.add_purchase, name='add_purchase'),
    path('pos/products/add_supply/', views.add_supply, name='add_supply'),
    path('pos/products/add/product/', views.add_product, name='add_product'),
    path('pos/products/add/expenses/', views.add_expense, name='add_expense'),
    path('pos/history/', views.history, name='history'),
    path('pos/history/supply', views.supply_history, name='supply_history'),

    path('pos/sales_?expenses/', views.sales_expenses, name="sales_expenses"),
    path('pos/sales_?expenses/<int:year>/', views.sales_expenses, name="sales_expenses"),
    path('pos/sales_?expenses/<int:year>/<int:month>/', views.sales_expenses, name="sales_expenses"),
    path('pos/sales_?expenses/<int:year>/<int:month>/<int:day>/', views.sales_expenses, name="sales_expenses"),

    path('pos/statistics/', views.statistics, name="statistics"),

]

pos/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=100)
    available_quantity = models.PositiveIntegerField(default=0)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', '-date_created',)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f'<Product: {self.name[:10]}>'
    

class Purchase(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=15, decimal_places=2)
    date_created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-date_created',)
    
    def __repr__(self):
        return f'<Purchase: GH{self.total_amount} by {self.username}>'

    def save(self, *args, **kwargs):
        self.product.available_quantity -= self.quantity
        self.price = self.price * int(self.quantity)
        self.product.save()
        super(Purchase, self).save(*args, **kwargs)

class Supply(models.Model):
    product = models.ForeignKey(Product, related_name="supplies", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return f'{self.quantity} of {self.product.name}'
    
    def __repr__(self):
        return f'<Supply: {self.product.name} {self.quantity}>'
    
    def save(self, *args, **kwargs):
        self.product.available_quantity = int(self.product.available_quantity) + int(self.quantity)
        self.product.save()
        super(Supply, self).save(*args, **kwargs)

class Expense(models.Model):
    description = models.CharField(max_length=600)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-date',)
    
    def __str__(self):
        return self.description

pos/forms.py
from django import forms
from . import models

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = models.Purchase
        fields = ("product", "quantity", "price")


class SupplyForm(forms.ModelForm):
    class Meta:
        model = models.Supply
        fields = ('product', 'quantity')


class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields  = ('name', 'available_quantity', 'description')


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = models.Expense
        fields = ('description', 'amount')

pos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.db.models import Q 
from django.contrib.auth.decorators import login_required
import datetime
from . import models
from . import forms
# Create your views here.
def index(request):
    return render(request, 'index.html')

@login_required
def pos_index(request):
    return render (request, 'pos/index.html', 
    {
            'supply_form': forms.SupplyForm(),
            'product_form': forms.ProductForm(),
            'expense_form': forms.ExpenseForm(),
    })

@login_required
def products_list(request):
    
    products_list = models.Product.objects.all()
    
    search_query = request.GET.get('q')
    if search_query:
        products_list = products_list.filter(
            Q(name__icontains = search_query) |
            Q(description__icontains = search_query) 
        )
    #items = models.Product.objects.all()

    return render(
        request,
        'pos/products_list.html',
        {
            'products': products_list,
            'purchase_form': forms.PurchaseForm(),
        }
    )

@login_required
def add_purchase(request):
    if request.method == 'POST':
        form = forms.PurchaseForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Item successfuly purchased")
            return redirect('pos:products_list')
        else:
            messages.warning(request, "Error. Transaction Faield")
    else:
        form = forms.PurchaseForm()

    return redirect('pos:products_list')


@login_required
def add_supply(request):
    if request.method == "POST":
        form = forms.SupplyForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Supply added Successfully")
            redirect_url = request.GET.get("next")
            if redirect_url is not None:
                redirect(redirect_url)
        else:
            messages.warning(request, "There was an error in the data entered")

    return redirect('pos:products_list')


@login_required
def add_product(request):
    if request.method == "POST":
        form = forms.ProductForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Product Successfully added")
            redirect_url = request.GET.get("next")
            if redirect_url is not None:
                redirect(redirect_url)
    return redirect('pos:products_list')

@login_required
def add_expense(request):
    if request.method == 'POST':
        form = forms.ExpenseForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'Expense Successfully added')
            #if redirect_url is not None:
                #redirect(redirect_url)
    return redirect('pos:add_expense')

@login_required
def history(request):
    return render(request, "pos/history.html")


@login_required
def supply_history(request):
    supplies = models.Supply.objects.all()
    return render(request, 'pos/supply_history.html',
    {
        'supplies': supplies,
    })


@login_required
def sales_expenses(request, year=None, month=None, day=None, item=None):
    if year and month and day:
        purchases = models.Purchase.objects.filter(date_created__year=year, date_created__month=month, date_created__day=day)
        expenses = models.Expense.objects.filter(date__year=year, date__month=month, date__day=day)
    elif year and month:
        purchases = models.Purchase.objects.filter(date_created__year=year, date_created__month=month)
        expenses = models.Expense.objects.filter(date__year=year, date__month=month)
    elif year:
        purchases = models.Purchase.objects.filter(date_created__year=year)
        expenses = models.Expense.objects.filter(date__year=year)
    else:
        purchases = models.Purchase.objects.all()
        expenses = models.Expense.objects.all()

    total_purchases = 0
    total_expenses = 0
    for i in purchases:
        total_purchases += i.price
    for x in expenses:
        total_expenses += x.amount
    
    net_total = total_purchases - total_expenses

    if item:
        itempurchases = purchases.objects.filter(product=item)

    return render(
        request, 
        'pos/purchase_history.html', 
        {
            'purchases': purchases,
            'expenses': expenses,
            'year': year,
            'month': month,
            'day': day,
            'total_purchases': total_purchases,
            'total_expenses': total_expenses,
            'net_total': net_total,
            'item': item,
        }
    )

@login_required
def statistics(request):
    products = models.Product.objects.filter(available_quantity=0)
    return render(request, "pos/statistics.html", {
        "products": products,
    })

templates/pos/add_expense.html
{% load crispy_forms_tags %}


<div class="container bg-gray p-5" style="width: 50%;">
    <h2>Add Expenses</h2>

    <form method="POST" action="{% url 'pos:add_expense' %}?next=/" enctype="multipart/form-data">
        {% csrf_token %}
        {{ expense_form | crispy }}
        <p><input class="btn btn-info btn-large btn-block" type="submit" value="Add Expense"> </p>
    </form>

</div>

templates/pos/add_purchase.html
{% load crispy_forms_tags %}

<div class="container bg-gray p-5" style="width: 50%;">
    <div class="d-flex justify-content-between">
        <h2>Add Purchase</h2>
        <h2 class="text-white display-4 pl-1">GH <span id="price">0.0</span></h2>
    </div>

    <form method="POST" action="{% url 'pos:add_purchase' %}?next=/" enctype="multipart/form-data">
        {% csrf_token %}
        {{ purchase_form | crispy }}
        
        <input type="submit" name="" value="Complete" class="btn btn-success btn-md">
    </form>
</div>

templates/pos/add_supply.html
{% load crispy_forms_tags %}


<div class="container bg-gray p-5" style="width: 50%;">
    <h2>Add Supply</h2>

    <form method="POST" action="{% url 'pos:add_supply' %}?next=/">
        {% csrf_token %}
        {{ supply_form | crispy }}
        <p><input class="btn btn-info btn-large btn-block" type="submit" value="Add Supply"> </p>
    </form>

</div>

templates/pos/drug_history.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<br>


<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <form class="header-search-form shadow" method="GET" action="{% url 'pos:drug_history' %}">

                <input id="input" class="" name="q" type="text" placeholder="Search ....">
                <input type="submit" value="Search" class="btn btn-info" style="background-color: rgb(0, 192,192)">

            </form>
        </div>
        <div class="col-2"></div>
    </div>
</div>

<br>

<div class="container">
    <div class="row">
        {% if product_sold %}
        <div class="col-md-4 bg-info p-2 mr-3 text-white text-center shadow">
            <h6>Total Quantity Sold : <span class="text-black"> <strong style="font-size: 20px;">
                        {{ qty }} </strong> </span></h6>
        </div>
        <div class="col-md-4 bg-success p-2 text-white text-center shadow">
            <h6>Total Amount : Ghc <span class="text-black"> <strong style="font-size: 20px;">
                        {{ product_sold }} </strong> </span></h6>
        </div>
        {% endif %}
    </div>
</div>

<div class="container pt-4">
    <div class="row ">
        <div class="col-12">
            <table class="table shadow  table-hover table-striped white-bg">
                <thead class="bg-dark text-white">
                    <tr>
                        <th> Product </th>
                        <th> Date </th>
                        <th> Qty Sold </th>
                        <th> Total amount </th>
                        <th> Available quantity </th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in getDrug %}
                    <tr>
                        <td> {{ item.product }} </td>
                        <td> {{ item.date }} </td>
                        <td> {{ item.quantity }} </td>
                        <td> Ghc {{ item.total_amount }} </td>
                        <td>
                            {{ item.qty }}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="7">
                            <h4>No item found </h4>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

templates/pos/drughistory.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<br>


<div class="container">
    <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <form class="header-search-form shadow" method="GET" action="{% url 'pos:drughistory' %}">
            
            <input id="input" class="" name="q" type="text" placeholder="Search ....">
            <input type="submit" value="Search" class="btn btn-info" style="background-color: rgb(0, 192,192)">

        </form>
    </div>
    <div class="col-2"></div>
</div>
</div>

<br>

<div class="container">
    <div class="col-md-4 bg-info p-2 text-white text-center shadow">
        <h6>Drugs Sold = Ghc <span class="text-black"> <strong style="font-size: 20px;">
            {{ product_sold }} </strong> </span></h6>
    </div>
</div>

<div class="container pt-5">
    <div class="row">
        <div class="col-12">
            <table class="table shadow  table-hover table-striped">
                <thead class="bg-dark text-white">
                    <tr>
                        <th> Product </th>
                        <th> Date </th>
                        <th> Qty Sold </th>
                        <th> Total amount </th>
                        <th> Available quantity </th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in getDrug %}
                    <tr>
                        <td> {{ item.product }} </td>
                        <td> {{ item.date }} </td>
                        <td> {{ item.quantity }} </td>
                        <td> Ghc {{ item.total_amount }} </td>
                        <td>
                            {{ item.qty }}
                        </td>
                    </tr>
                    {% empty %}
                    <tr >
                        <td colspan="7"> <h4>No item found </h4> </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

templates/pos/history.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<h5 class="text-center mt-3">
    <p class="display-3 text-white">HISTORY</p>
</h5>
<div class="container">
    <div class="row mt-5">
        <div class="col-md-6 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="{% url 'pos:sales_expenses' %}" class="link">
                    <img class="ind-img" src="{% static 'images/purchases.png' %}" alt="img not found">
                    <h3 class="">Sales & Expenses</h3>
                </a>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="{% url 'pos:supply_history' %}" class="link" id="supply-link">
                    <img class="ind-img" src="{% static 'images/supplies.png' %}" alt="img not found">
                    <h3 class=""> Supply</h3>
                </a>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/pos/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="{% url 'pos:products_list' %}" class="link">
                    <img class="ind-img" src="{% static 'images/purchases.png' %}" alt="img not found">
                    <h3 class="">Purchase</h3>
                </a>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="m-3 card grey-bg shadow">
                <a class="link" id="product-link" href="#">
                    <img class="ind-img" src="{% static 'images/itemlist.png' %}" alt="img not found">
                    <h3 class=""><i class="fas fa-plus"></i> Products</h3>
                </a>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="#" class="link" id="supply-link">
                    <img class="ind-img" src="{% static 'images/supplies.png' %}" alt="img not found">
                    <h3 class=""><i class="fas fa-plus"></i> Supply</h3>
                </a>
            </div>
        </div>

        <div class="col-md-4 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="#" class="link" id="expense-link">
                    <img class="ind-img" src="{% static 'images/expenses.png' %}" alt="img not found">
                    <h3 class=""><i class="fas fa-plus"></i> Expenses</h3>
                </a>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="{% url 'pos:history' %}" class="link">
                    <img class="ind-img" src="{% static 'images/history.png' %}" alt="img not found">
                    <h3 class="">History</h3>
                </a>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="{% url 'pos:statistics' %}" class="link">
                    <img class="ind-img" src="{% static 'images/statistics.png' %}" alt="img not found">
                    <h3 class="">Statistics</h3>
                </a>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="{% url 'admin:index' %}" class="link">
                    <img class="ind-img" src="{% static 'images/admin.png' %}" alt="img not found">
                    <h3 class="">Admin</h3>
                </a>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="{% url 'pos:logout' %}" class="link">
                    <img class="ind-img" src="{% static 'images/logout.png' %}" alt="img not found">
                    <h3 class="">Log Out</h3>
                </a>
            </div>
        </div>
    </div>
</div>





<div class="myoverlay full-screen" id="product-view">
    <i class="myclose btn btn-danger">X</i>
    <div class="container">
        {% include 'pos/add_product.html' %}
    </div>
</div>

<div class="myoverlay full-screen" id="supply-view">
    <i class="myclose btn btn-danger">&times;</i>
    <div class="container">
        {% include 'pos/add_supply.html' %}
    </div>
</div>

<div class="myoverlay full-screen" id="expense-view">
    <i class="myclose btn btn-danger">X</i>
    <div class="container">
        {% include 'pos/add_expense.html' %}
    </div>
</div>

<script async>
    document.querySelector("#product-link").addEventListener("click", function (e) {
        document.querySelector("#product-view").classList.toggle("show");
    });

    document.querySelector("#supply-link").addEventListener("click", function (e) {
        document.querySelector("#supply-view").classList.toggle("show");
    });

    document.querySelector("#expense-link").addEventListener("click", function (e) {
        document.querySelector("#expense-view").classList.toggle("show");
    });

    let closes = document.getElementsByClassName("myclose");
    for (let i = 0; i < closes.length; i++) {
        closes[i].addEventListener('click', function (e) {
            this.parentNode.classList.toggle("show");
        });
    }
</script>

{% endblock %}

templates/pos/navbar.html
    <!-- =========== NAVBAR ========== -->

    <div class="">
        <nav class="navbar navbar-expand-lg navbar-light " style="background-color:rgb(0, 192,192);">
            <div class="container">
                <a class="navbar-brand text-center" href="{% url 'pos:items_list' %}" style="color: white;"> <B> MEDICARE
                        <br>
                        CHEMICALS</B></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    {% if request.user.is_authenticated %}
                    <ul class="navbar-nav ">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'pos:items_list' %}"> <i class="fas fa-home"></i> <b> Home
                                </b></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" id="add-supply-link"> <i class="fas fa-plus"></i> <b> Supply
                                </b></a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" id="add-product-link" href="#"> <i class="fas fa-plus"></i> <b>
                                    Product
                                </b></a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" id="add-purchase-link" href="#"> <i class="fas fa-plus"></i> <b>
                                    Purchase
                                </b></a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" id="add-expense-link"" href=" #"> <i class="fas fa-plus"></i> <b>
                                    Expense </b></a>
                        </li>

                        <li class="nav-item  dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropDownMenuLink-333"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> History </a>
                            <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                                <a href="{% url 'pos:history' %}" class="dropdown-item"> > Sales & Expenses </a>
                                <a href="{% url 'pos:drug_history' %}" class="dropdown-item"> > Products </a>
                                <a href="{% url 'pos:supply_history' %}" class="dropdown-item"> > Supplies </a>
                            </div>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'pos:logout' %}"> <i class="fas fa-sign-out-alt"></i> <b> Log
                                    Out </b> </a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'admin:index' %}"> <i class="fas fa-sign-out-alt"></i> <b>
                                    Admin </b> </a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </div>

templates/pos/purchase_history.html
{% extends 'base.html' %}

{% block content %}
<div class="container pl-8 pr-8">
    <div class="container">
        <div class="row">
        <div class="col-12 mt-3 text-center"><h2 class="display-4 text-white">SALES & EXPENSES</h2></div>
        </div>
    </div>
    <hr>
    <br>

    <div class="d-flex justify-content-center row pb-3">


        <div class="col-3 mt-2">
            <input type="number" class="form-control" placeholder="day" id="day">
        </div>
        <div class="col-3 mt-2">
            <input type="number" class="form-control" placeholder="month" id="month">
        </div>
        <div class="col-3 mt-2">
            <input type="number" class="form-control" placeholder="year" id="year">
        </div>

        <div class="col-3">
            <button class="btn btn-success" id="filter">Search</button>
        </div>

        <script>
            let year = document.getElementById("year");
            let month = document.getElementById("month");
            let day = document.getElementById("day");
            let filter = document.getElementById("filter");

            filter.addEventListener("click", function (e) {

                let _year = parseInt(year.value);

                let _month = parseInt(month.value);

                let _day = parseInt(day.value);
                let route = "{% url 'pos:sales_expenses' %}";
                if (_year !== NaN && _year > 0) {
                    route += + _year;
                    if (_month !== NaN && _month > 0) {
                        route += '/' + _month;
                        if (_day !== NaN && _day > 0) {
                            route += '/' + _day;
                        }
                    }
                }
                window.location = route;
            });
        </script>
    </div>
    <hr>
    {% if day or month or year %}
    <div class="container">
        <div class="row text-center">
            <div class="col-md-4 bg-success p-2 text-white">
                <h6>Total Purchase = Ghc <span class="text-black"> <strong style="font-size: 20px;">
                    {{ total_purchases }}</strong> </span></h6>
            </div>
            <div class="col-md-4 bg-info p-2 text-white">
                <h6>Total Expenses = Ghc <span class="text-black"> <strong style="font-size: 20px;">
                    {{ total_expenses }} </strong> </span></h6>
            </div>
            
            <div class="col-md-4 bg-{% if net_total < 0 %}danger{% else %}warning{% endif %} p-2">
                <h6>NET SALES = Ghc <span class="text-black"> <strong style="font-size: 20px;">
                            {{ net_total }} </strong> </span></h6>
            </div>
        </div>
    </div>
    <hr>
    {% endif %}
    <br>
    <div class="row">
        <div class="col-md-7">
            <div class="container">
                <h2 class="display-5 text-white">SALES</h2>
            </div>
            <table class="table shadow table-striped table-hover white-bg">
                <thead class="bg-dark text-white">
                    <tr>
                        <th> Date </th>
                        <th> Items Sold </th>
                        <th> Qty </th>
                        <th>Total Sales</th>
                    </tr>
                </thead>
                <tbody>
                    {% for purchase in purchases %}
                    <tr>
                        <td>{{ purchase.date_created }}</td>
                        <td>{{ purchase.product }}</td>
                        <td>{{ purchase.quantity }}</td>

                        <td><b> Ghc {{ purchase.price }}</b></td>

                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="6">
                            <h1>There are no purchases...</h2>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-md-5">
            <div class="container">
                <h2 class="display-5 text-white">EXPENSES</h2>
            </div>
            <table class="table shadow table-striped white-bg">
                <thead class="bg-dark text-white">
                    <tr>
                        <th> Date </th>
                        <th> Description </th>
                        <th> Amount </th>
                    </tr>
                </thead>
                <tbody>
                    {% for expense in expenses %}
                    <tr>
                        <td>{{ expense.date }}</td>

                        <td>{{ expense.description }}</td>

                        <td>{{ expense.amount }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="7">
                            <h1>There are no Expenses...</h2>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<br>
<br>
<br>



{% endblock %}

templates/pos/statistics.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col-12 float-left text-center"><h2 class="display-4 text-white">Out of Stock</h2></div>
    </div>
</div>

<div class="container pt-3">
    <div class="row">
        <div class="col-12">
            <table class="table shadow  table-hover table-striped white-bg">
                <thead class="bg-dark text-white">
                    <tr>
                        <th> # </th>
                        <th> Product  </th>
                        <th> Quantity </th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                    <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ product.name}} </td>
                        <td> {{ product.available_quantity }} </td>
                    </tr>
                    {% empty %}
                    <tr >
                        <td colspan="7"> <h4>No product out of stock </h4> </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}