bank/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from . import views

app_name = "bank"

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('bank/index', views.bank_index, name="bank_index"),
    path('bank/account/registration', views.register, name="bank_register_account"),
    path('bank/account/edit/<int:pk>/', views.edit_profile, name="edit_profile"),
    path('bank/account/delete/<int:pk>/', views.delete_account, name="delete_account"),
    path('bank/deposite/to/<int:pk>/', views.deposite, name="deposite"),
    path('bank/withdraw/from/<int:pk>/', views.withdrawal, name="withdrawal"),
    path('bank/profile/<int:pk>/', views.profile, name="profile"),

    path('bank/profile/transactions/<int:pk>/', views.transactions, name="transactions"),
    path('bank/profile/transactions/<int:pk>/<int:year>/', views.transactions, name="transactions"),
    path('bank/profile/transactions/<int:pk>/<int:year>/<int:month>/', views.transactions, name="transactions"),
    path('bank/profile/transactions/<int:pk>/<int:year>/<int:month>/<int:day>/', views.transactions, name="transactions"),
]

bank_pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pos.urls')),
    path('', include('bank.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from . import views

app_name = "pos"

urlpatterns = [
    path('', views.index, name="index"),
    path('pos/login/', LoginView.as_view(), name="login"),
    path('pos/logout/', LogoutView.as_view(), name="logout"),
    path('pos/admin/', admin.site.urls, name='admin'),
    path('pos/index/', views.pos_index, name='pos_index'),
    path('pos/products/list/', views.products_list, name='products_list'),
    path('pos/products/add_purchase/', views.add_purchase, name='add_purchase'),
    path('pos/products/add_supply/', views.add_supply, name='add_supply'),
    path('pos/products/add/product/', views.add_product, name='add_product'),
    path('pos/products/add/expenses/', views.add_expense, name='add_expense'),
    path('pos/history/', views.history, name='history'),
    path('pos/history/supply', views.supply_history, name='supply_history'),

    path('pos/sales_?expenses/', views.sales_expenses, name="sales_expenses"),
    path('pos/sales_?expenses/<int:year>/', views.sales_expenses, name="sales_expenses"),
    path('pos/sales_?expenses/<int:year>/<int:month>/', views.sales_expenses, name="sales_expenses"),
    path('pos/sales_?expenses/<int:year>/<int:month>/<int:day>/', views.sales_expenses, name="sales_expenses"),

    path('pos/statistics/', views.statistics, name="statistics"),

]

templates/bank_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Medicare POS</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- <link rel="stylesheet" href="{% static 'css/tailwind.min.css' %}" > -->

</head>

<body>

    {% include 'bank_navbar.html' %}

    {% if messages %}
        {% for message in messages %}
        <div class="container alert alert-{{ message.tags }} alert-dismissible fade show py-3" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}
    

    {% block content %}

    {% endblock %}

    <script src="{% static 'js/fontawesome.min.js' %}"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/jquery-slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/mdb.min.js' %}"></script>


</body>

</html>

templates/bank_navbar.html
<div class="bg-dark container-fluid d-flex flex-row justify-content-between">
    <div>
        <a href="{% url 'bank:logout' %}" class="btn btn-lg bg-danger text-dark"><i class="fas fa-sign-out-alt text-white fa-lg"></i></a>
        <a href="{% url 'bank:bank_index' %}" class="btn btn-lg white-bg text-dark"><i class="fas fa-home fa-lg"></i></a>
        <a class="text-center text-white title">AUTHENTIC BANKING</a>
    </div>
    <div class="text-white pt-3" style="font-size: 0.5rem;">
        software developed by <br> 
        <span>TECHPRINT Solutions</span> <br>
        <small>+233 243186008</small> 
    </div>
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Medicare POS</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- <link rel="stylesheet" href="{% static 'css/tailwind.min.css' %}" > -->

</head>

<body>

    {% include 'navbar.html' %}

    {% if messages %}
        {% for message in messages %}
        <div class="container alert alert-{{ message.tags }} alert-dismissible fade show py-3" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}
    

    {% block content %}

    {% endblock %}

    <script src="{% static 'js/fontawesome.min.js' %}"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/jquery-slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/mdb.min.js' %}"></script>


</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row text-center align-items-center justify-content-center">
       <h2 class="mt-4 text-white">AUTHENTIC Ventures &  AUTHENTIC Banking </h2>
    </div>
</div>

<div class="container">
    <div class="row text-center d-flex align-items-center py-5 justify-content-center h-min-100vh">
        <div class="col-md-6 text-center">
            <div class="m-3 card grey-bg shadow">
                <a href="{% url 'bank:bank_index' %}" class="link">
                    <img class="ind-img" src="{% static 'images/purchases.png' %}" alt="img not found">
                    <h3 class=""> BANKING </h3>
                </a>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="m-3 card grey-bg shadow">
                <a class="link" href="{% url 'pos:pos_index' %}">
                    <img class="ind-img" src="{% static 'images/itemlist.png' %}" alt="img not found">
                    <h3 class=""> POS </h3>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/navbar.html
<div class="bg-dark container-fluid d-flex flex-row justify-content-between">
    <div>
        <a href="{% url 'pos:logout' %}" class="btn btn-lg bg-danger text-dark"><i class="fas fa-sign-out-alt text-white fa-lg"></i></a>
        <a href="/" class="btn btn-lg white-bg text-dark"><i class="fas fa-home fa-lg"></i></a>
        <a class="text-center text-white title">AUTHENTIC VENTURES</a>
    </div>
    <div class="text-white pt-3" style="font-size: 0.5rem;">
        software developed by <br> 
        <span>TECHPRINT Solutions</span> <br>
        <small>+233 243186008</small> 
    </div>
</div>