bank/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from . import views

app_name = "bank"

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('bank/index', views.bank_index, name="bank_index"),
    path('bank/account/registration', views.register, name="bank_register_account"),
    path('bank/account/edit/<int:pk>/', views.edit_profile, name="edit_profile"),
    path('bank/account/delete/<int:pk>/', views.delete_account, name="delete_account"),
    path('bank/deposite/to/<int:pk>/', views.deposite, name="deposite"),
    path('bank/withdraw/from/<int:pk>/', views.withdrawal, name="withdrawal"),
    path('bank/profile/<int:pk>/', views.profile, name="profile"),

    path('bank/profile/transactions/<int:pk>/', views.transactions, name="transactions"),
    path('bank/profile/transactions/<int:pk>/<int:year>/', views.transactions, name="transactions"),
    path('bank/profile/transactions/<int:pk>/<int:year>/<int:month>/', views.transactions, name="transactions"),
    path('bank/profile/transactions/<int:pk>/<int:year>/<int:month>/<int:day>/', views.transactions, name="transactions"),
]

bank_pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pos.urls')),
    path('', include('bank.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from . import views

app_name = "pos"

urlpatterns = [
    path('', views.index, name="index"),
    path('pos/login/', LoginView.as_view(), name="login"),
    path('pos/logout/', LogoutView.as_view(), name="logout"),
    path('pos/admin/', admin.site.urls, name='admin'),
    path('pos/index/', views.pos_index, name='pos_index'),
    path('pos/products/list/', views.products_list, name='products_list'),
    path('pos/products/add_purchase/', views.add_purchase, name='add_purchase'),
    path('pos/products/add_supply/', views.add_supply, name='add_supply'),
    path('pos/products/add/product/', views.add_product, name='add_product'),
    path('pos/products/add/expenses/', views.add_expense, name='add_expense'),
    path('pos/history/', views.history, name='history'),
    path('pos/history/supply', views.supply_history, name='supply_history'),

    path('pos/sales_?expenses/', views.sales_expenses, name="sales_expenses"),
    path('pos/sales_?expenses/<int:year>/', views.sales_expenses, name="sales_expenses"),
    path('pos/sales_?expenses/<int:year>/<int:month>/', views.sales_expenses, name="sales_expenses"),
    path('pos/sales_?expenses/<int:year>/<int:month>/<int:day>/', views.sales_expenses, name="sales_expenses"),

    path('pos/statistics/', views.statistics, name="statistics"),

]

bank/models.py
from django.db import models

from django.contrib.auth.models import User
import datetime
from django.urls import reverse
# Create your models here.
ACCOUNT_CHOICES = (
    ("Susu Banking", "Susu Banking"),
    ("Current Account", "Current Account"),
    ("Fixed Deposite", "Fixed Deposite"),
)
SEX_CHOICES = (
    ("M", "M"),
    ("F", "F"),
)
ID_CHOICES = (
    ("Voters ID","Voters ID"),
    ("Ghana Card","Ghana Card"),
    ("NHIS","NHIS"),
    ("Passport","Passpord"),
    ("Drivers Licensed","Drivers Licensed"),
)
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    phone_number = models.CharField(max_length=10, null=True, blank=True)
    image = models.ImageField(upload_to=("profile_image/"), null=True, blank=True)
    digital_address = models.CharField(max_length=12)
    sex = models.CharField(choices=SEX_CHOICES, max_length=2)
    dob = models.DateField()

    next_of_kin = models.CharField(max_length=100, null=True, blank=True)
    next_of_kin_phone_number = models.CharField(max_length=10, null=True, blank=True)
    next_of_kin_digital_address = models.CharField(max_length=12, null=True, blank=True)

    id_type = models.CharField(choices=ID_CHOICES, max_length=50)
    id_number = models.PositiveIntegerField()

    account_number = models.CharField(max_length=10)
    account_type = models.CharField(choices=ACCOUNT_CHOICES,  max_length=100)
    account_balance = models.FloatField()
    
    date_created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-date_created",)

    def get_absolute_url(self) -> str:
        return reverse("bank:profile", kwargs={"pk": self.user.pk})

class Deposite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.FloatField()
    date_created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-date_created",)

    def save(self, *args, **kwargs):
        self.user.profile.account_balance +=  float(self.amount)
        self.user.profile.save()
        super(Deposite, self).save(*args, **kwargs)


class Withdrawal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.FloatField()
    date_created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-date_created",)
        
    def save(self, *args, **kwargs):
        self.user.profile.account_balance -=  float(self.amount)
        self.user.profile.save()
        super(Withdrawal, self).save(*args, **kwargs)

bank/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import HttpResponseRedirect, redirect
from django.conf import settings
from django.db import transaction

class DateInput(forms.DateInput):
    input_type = "date"

class RegisterForm(forms.ModelForm):
    #password2 = forms.CharField(label="Re-enter password", widget=forms.PasswordInput, )
    #password = forms.CharField(widget=forms.PasswordInput,  help_text="must be more than 6 characters")

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            #"password",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 '
                    'rounded py-3 px-4 leading-tight '
                    'focus:outline-none focus:bg-white '
                    'focus:border-gray-500'
                )
            })

    def clean_password2(self, *args, **kwargs):
        data = self.cleaned_data
        p = data["password2"]
        p_1 = data["password"]
        if len(p) < 6:
            raise forms.ValidationError("Your password should be 6 or more characters")
        if p == p_1:
            return p
        raise forms.ValidationError("Your passwords do not match")

class ProfileForm(forms.ModelForm): 
    dob = forms.DateField(
        widget=DateInput,
        label="Date of Birth",
    )
    image = forms.FileField(
        label="Passport Picture",
    )
    class Meta:
        model = models.Profile
        fields = ("phone_number","image","digital_address","sex","dob","next_of_kin","next_of_kin_phone_number",
                    "next_of_kin_digital_address", "account_type", "account_balance", "id_type", "id_number",
        )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 '
                    'rounded py-3 px-4 leading-tight '
                    'focus:outline-none focus:bg-white '
                    'focus:border-gray-500'
                )
            })

class DepositeForm(forms.ModelForm):
    class Meta:
        model = models.Deposite
        fields = ("amount",)

class WithdrawalForm(forms.ModelForm):
    class Meta:
        model = models.Withdrawal
        fields = ("amount",)

bank/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from . import models
from django.db.models import Q 
from . import forms
# Create your views here.
from django.shortcuts import redirect, get_object_or_404
import random
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required

@staff_member_required
def bank_index(request):
    total_balance = 0
    num=0
    customers = User.objects.all()
    #customers = models.Profile.objects.all()

    search_query = request.GET.get('q')
    if search_query:
        customers = customers.filter(
            Q(profile__account_number = search_query))
    
    for customer in customers:
        if hasattr(customer, "profile"):
            num += 1
            total_balance += customer.profile.account_balance

    #for customer in customers:
    #    total_balance += customer.account_balance

    return render(request, "bank/index.html",
        {
            "customers": customers,
            "search_query": search_query,
            "total_balance":  "{:.2f}".format(total_balance),
            "num": num,
        }
    )

@staff_member_required
def register(request):
    if request.method == 'POST':
        user_form = forms.RegisterForm(data=request.POST, files=request.FILES)
        profile_form = forms.ProfileForm(data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            rand = random.randint(1,100000)
            user = user_form.save(commit=False)
            user_profile = profile_form.save(commit=False)
            if user_profile.phone_number:
                user.username = user_profile.phone_number + str(rand)
            else:
                user.username = str(rand)
            user.password = "james.user"
            user.password2 = "james.user"
            user.save()

            user_profile.user = user
            user_profile.account_number = str(settings.ACCOUNT_NUMBER_START_FROM + user.id)
            user_profile.save()

            messages.success(request, f"Account Succesfully Created with an account number '{user_profile.account_number}'. ")
            return redirect("/bank/index")
        else:
            messages.warning(request, "invalid data entry. plase check and try again")
    else:
        user_form = forms.RegisterForm()
        profile_form = forms.ProfileForm()
    
    return render(request, "registration/register.html",{
        "user_form": user_form,
        "profile_form": profile_form,
    })

@staff_member_required
def deposite(request, pk:int):
    user = get_object_or_404(models.User, pk=pk)

    if request.method == 'POST':
        form = forms.DepositeForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            deposite = form.save(commit=False)
            deposite.user = user
            deposite.save()
            messages.success(request, f"Succesfully deposited GH₵{deposite.amount} to {user.profile.account_number}.  Current balance GH₵{deposite.user.profile.account_balance} ")
            return redirect('/bank/index')
        else:
            messages.warning(request, "Deposite Error. Not Successful")
    else:
        form = forms.DepositeForm()
    
    return render(request, "bank/deposite.html", {"form":form, "user": user,})



@staff_member_required
def withdrawal(request, pk:int):
    user = get_object_or_404(models.User, pk=pk)

    if request.method == 'POST':
        form = forms.WithdrawalForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            withdrawal = form.save(commit=False)
            if user.profile.account_balance >= withdrawal.amount:
                withdrawal.user = user
                withdrawal.save()
                messages.success(request, f"Succesfully withdrawn GH₵{withdrawal.amount} from {user.profile.account_number}. Current balance GH₵{withdrawal.user.profile.account_balance}  ")
                return redirect("/bank/index")
            else:
                messages.warning(request, f"Not Enough Funds")
        else:
            messages.warning(request, "withdrawal Error. Not Successful")
    else:
        form = forms.WithdrawalForm()
    
    return render(request, "bank/withdrawal.html", {"form":form, "user": user,})

@staff_member_required
def profile(request, pk:int):
    profile = get_object_or_404(models.Profile, user_id=pk)
    return render(request, "bank/profile.html",{"profile":profile,})

@staff_member_required
def transactions(request, pk:int, year=None, month=None, day=None):
    user = get_object_or_404(models.User, pk=pk)

    if year and month and day:
        deposites = models.Deposite.objects.filter(date_created__year=year, date_created__month=month, date_created__day=day, user=user)
        withdrawals = models.Withdrawal.objects.filter(date_created__year=year, date_created__month=month, date_created__day=day, user=user)
    elif year and month:
        deposites = models.Deposite.objects.filter(date_created__year=year, date_created__month=month, user=user)
        withdrawals = models.Withdrawal.objects.filter(date_created__year=year, date_created__month=month, user=user)
    elif year:
        deposites = models.Deposite.objects.filter( user=user, date_created__year=year)
        withdrawals = models.Withdrawal.objects.filter(user=user, date_created__year=year)
    else:
        deposites = models.Deposite.objects.filter(user=user)
        withdrawals = models.Withdrawal.objects.filter(user=user)
    return render(request, "bank/transactions.html",
        {   "deposites":deposites,
            "withdrawals":withdrawals,
            "year": year,
            "month": month,
            "day": day,
            "user": user,
        }
    )
@staff_member_required
def edit_profile(request, pk:int):
    user = get_object_or_404(models.User, pk=pk)
    profile = get_object_or_404(models.Profile, user=user)
    if request.method == 'POST':
        user_form = forms.RegisterForm(data=request.POST, files=request.FILES, instance=user)
        profile_form = forms.ProfileForm(data=request.POST, files=request.FILES, instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.password = "james.user"
            user.password2 = "james.user"
            user.save()
            profile_form.save()
            messages.success(request, "Profile successfully updated")
            return redirect(user.profile.get_absolute_url())
        else:
            messages.warning(request, "Error.please check and try again.")
    else:
        user_form = forms.RegisterForm(instance=user)
        profile_form = forms.ProfileForm(instance=profile)
    
    return render(request, "bank/edit_profile.html", {"user_form": user_form, "profile_form": profile_form})

@staff_member_required
def delete_account(request, pk:int):
    user = get_object_or_404(models.User, pk=pk)
    user.delete()
    user.save()
    messages.success(request, "Account Deleted successfully")
    return redirect("/")

templates/bank/deposite.html
{% extends 'bank_base.html' %}
{% block title %} Deposite {% endblock %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container">

    <div class="col-12 px-1">

        <div class="row d-flex align-items-center py-5 justify-content-center h-min-100vh">
            <div class="col-md-12">
                <div class="bg-gray px-3 px-sm-4 p-md-5 shadow white-bg">
                    <h3 class="text-center text-bolder text-dark">Deposite</h3>
                    <h5 class="text-center text-bolder text-dark"> Acc. #: {{ user.profile.account_number }}</h5>

                    <h5 class="text-center text-dark text-uppercase ">Name: {{ user.last_name }} {{ user.first_name }}
                    </h5>
                    <br>
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-error">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-error">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}


                    <form method="POST" enctype="multipart/form-data"
                        class="bg-white text-dark shadow-md rounded px-8 pt-6 pb-8 mb-4">
                        {% csrf_token %}
                        {{ form | crispy }}


                        <input id="submit" onclick="return confirm('Are you sure you want Deposite amount entered below to {{ user.profile.account_number }}')" class="btn btn-dark btn-large" type="submit"
                            value="Deposite">

                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/bank/index.html
{% extends 'bank_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 pt-2 mb-2 text-center d-flex flex-row justify-content-between">
            <h4 class="display-4 text-white">CUSTOMERS [{{num}}]</h2>
            <div class="">
                <a href="{% url 'bank:bank_register_account' %}" class="btn btn-lg btn-info"> <i class="fas fa-plus-circle mr-2"></i> New Registration</a>
                <a href="{% url 'bank:logout' %}" class="btn btn-lg btn-danger"> <i class="fas fa-user-lock mr-2"></i> Log Out</a>
                <b class="text-white"> bal: ₵ {{  total_balance }} </b>
            </div>
        </div>
    </div>
    <form class="header-search-form " method="GET" action="{% url 'bank:bank_index' %}">

        <input id="input" class="w-10" name="q" type="number" placeholder="Account Number ...."
        style="width: 100%;">
        <input type="submit" value="Search" class="btn btn-primary" style="background-color: rgb(0, 192,192)">

    </form>
    <br>
    <div class="row ">
        <div class="col-12">
            <table class="table shadow table-striped table-hover white-bg">
                <thead class="bg-dark text-white ">
                    <tr>
                        <th> Acc. # </th>
                        <th> Full Name</th>
                        <th> Acc. Type </th>
                        <th> Balance </th>
                        <th> Actions </th>
                    </tr>
                </thead>
                <tbody>
                    {% for customer in customers %}
                    {% if customer.profile %}
                    <tr>
                            <td>{{ customer.profile.account_number }}</td>
                            <td class="text-uppercase">{{ customer.last_name }} {{ customer.first_name }}</td>
                            <td>{{ customer.profile.account_type }}</td>
                            <td> GH₵ {{ customer.profile.account_balance }}</td>
                            <td> 
                                <div class="dropdown m-0 p-0">
                                    <span class="category-name" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-caret-down fa-lg"></i>
                                    </span>
                    
                                    <div class="dropdown-menu dropdown-warning  dropdown-menu-right shadow-sm"
                                        aria-labelledby="dropdownMenuButton"> 

                                        <a class="dropdown-item bg-success p-2 text-white" href="{% url 'bank:deposite' customer.pk %}">
                                            <i class="fas fa-hand-holding-usd mr-2"></i> Deposite
                                        </a>

                                        <a class="dropdown-item bg-danger p-2 text-white" href="{% url 'bank:withdrawal' customer.pk %}">
                                            <i class="fas fa-angle-double-left mr-2"></i> Redrawal
                                        </a>

                                        <a class="dropdown-item bg-secondary p-2 text-white" href="{% url 'bank:profile' customer.pk %}">
                                            <i class="fas fa-user mr-2"></i> Profile
                                        </a>
                    
                                    </div>
                                    
                                </div> 
                            </td>
                    </tr>
                    {% endif %}
                    {% empty %}
                    <tr>
                        <td colspan="7">
                            {% if search_query %}
                            <h3>Sorry, there is no customer with an account number <span class="text-danger">'{{ search_query }}' </span> </h3>
                            {% else %}
                            <h1>Sorry, You have not registered any customer yet.</h2>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="myoverlay full-screen" id="purchase-view">
    <i class="myclose btn btn-danger">X</i>
    <div class="container">
        {% include 'pos/add_purchase.html' %}
    </div>
</div>


<script async>

    document.querySelector("#purchase-link").addEventListener("click", function (e) {
        document.querySelector("#purchase-view").classList.toggle("show");
    });

    let closes = document.getElementsByClassName("myclose");
    for (let i = 0; i < closes.length; i++) {
        closes[i].addEventListener('click', function (e) {
            this.parentNode.classList.toggle("show");
        });
    }
</script>
{% endblock %}

templates/bank/profile.html
{% extends 'bank_base.html' %}
{% block title %} USER PROFILE {% endblock %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container">

    <div class="row">
        <div class="col-12 bg-white">
            <div class="text-center">
                <a href="{% url 'bank:transactions' profile.user.pk %}" class="btn btn-secondary"> Transactions </a>
                <a href="{% url 'bank:edit_profile' profile.user.pk %}" class="btn btn-info"> Edit Account </a>
                <a id="delete_account" href="{% url 'bank:delete_account' profile.user.pk %}" class="btn btn-danger"> 
                    Delete Account 
                    <script>
                        document.getElementById("delete_account").addEventListener('click', (e) => {
                            if (!confirm("Are you sure you want to delete this account?")) {
                                e.preventDefault();
                            }
                        });
                    </script>
                </a>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-4">
            <div class="text-center mb-2">
                <img src="{{ profile.image.url }}" alt="not found" width="200px" height="200px">
            </div>
            <div class="card shadow bg-white text-dark p-3">
                <ul class="list-unstyled">
                    <li>Account No.: <span style="font-weight: bolder; font-size: 24px;">{{ profile.account_number}}</span> </li>
                    <li>Account Type: <span style="font-weight: bolder; font-size: 24px;">{{ profile.account_type}}</span> </li>
                    <li>Bal: <span style="font-weight: bolder; font-size: 24px;">₵ {{ profile.account_balance }}</span> </li>


                </ul>
            </div>
        </div>

        <div class="col-md-8">
            <div class="bg-white shadow text-dark p-3 card">
                <br>
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-8 col-md-6 card shadow-none">
                            First Name
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.user.first_name }}
                            </span>
                        </div>
                        <div class="col-8 col-md-6 card shadow-none">
                            Last Name
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.user.last_name }}
                            </span>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-8 col-md-6 card shadow-none">
                            Phone Number
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.phone_number }}
                            </span>
                        </div>
                        <div class="col-8 col-md-6 card shadow-none">
                            Digital Adress
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.digital_address }}
                            </span>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-8 col-md-6 card shadow-none">
                            Gender
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.sex}}
                            </span>
                        </div>
                        <div class="col-8 col-md-6 card shadow-none">
                            Date of Birth
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.dob }}
                            </span>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-8 col-md-6 card shadow-none">
                            Next of Kin [full name]
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.next_of_kin }}
                            </span>
                        </div>
                        <div class="col-8 col-md-6 card shadow-none">
                            Next of Kin Phone Number
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.next_of_kin_phone_number }}
                            </span>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-8 col-md-6 card shadow-none">
                            Next of Kin Digital Adress
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.next_of_kin_digital_address }}
                            </span>
                        </div>
                        <div class="col-8 col-md-6 card shadow-none">
                            Registered Date
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.user.date_joined }}
                            </span>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-8 col-md-6 card shadow-none">
                            ID Type
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.id_type }}
                            </span>
                        </div>
                        <div class="col-8 col-md-6 card shadow-none">
                            ID No.
                            <span style="background-color: aliceblue;" class="p-2 text-uppercase">
                                {{ profile.id_number }}
                            </span>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-8 col-md-6 card shadow-none">
                            E-mail
                            <span style="background-color: aliceblue;" class="p-2">
                                {{ profile.user.email }}
                            </span>
                        </div>
                    </div>

                    
                </div>
         
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/bank/withdrawal.html
{% extends 'bank_base.html' %}
{% block title %} Withdraw {% endblock %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container">

    <div class="col-12 px-1">

        <div class="row d-flex align-items-center py-5 justify-content-center h-min-100vh">
            <div class="col-md-12">
                <div class="bg-gray px-3 px-sm-4 p-md-5 shadow white-bg">
                    <h3 class="text-center text-bolder text-dark">Withdraw</h3>
                    <h5 class="text-center text-bolder text-dark"> Acc. #: {{ user.profile.account_number }}</h5>

                    <h5 class="text-center text-dark text-uppercase ">Name: {{ user.last_name }} {{ user.first_name }} </h5>
                    <br>
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-error">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-error">
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                    {% endif %}


                    <form method="POST" enctype="multipart/form-data" class="bg-white text-dark shadow-md rounded px-8 pt-6 pb-8 mb-4">
                        {% csrf_token %}
                        
                        {{ form | crispy }}

                        <input id="submit" onclick="return confirm('Are you sure you want Withdraw amount entered below from {{ user.profile.account_number }}')" class="btn btn-dark btn-large" type="submit"
                            value="Withdraw">
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}